### ISSUE TITLE
Fix bugs to reach MVP

### ISSUE THREAD

**Issue by DangelTheMangel** [DiscoLucas/P7-Project#45]
- [x] Water puzzel stopped working
- [x] vents stopped working
- [x] damage have not been setup in main scene
- [x] PickUp Does not work (not setup) [Need to be setup for egg and valve]
- [x] Huds Egg pickup and drop not called 
- [x] Part that falls down does not work...
- [x] No indecator for exit and that you need the egg
- [x]  move levers to playerhight
- [ ] make the scene darker and scaryere
- [x] death colum not added

**Comment by DangelTheMangel** [comment]
- [ ] make so Walter damages you

**Comment by Dange1TheMange1** [comment]
- [ ] Gamemanager monster not set in GOAP
- [ ] Make it more apparant that you can interact with things
