### ISSUE TITLE
Emma's list of problems

### ISSUE THREAD

**Issue by Kiliopo** [DiscoLucas/P7-Project#50]

**Comment by Kiliopo** [comment]
- [ ] Bigger “you need the egg” hitbox at the exit
- [ ] Close the hole at the exit tube.
- [ ] Light above the door changes from red to green when switch is flipped
- [ ] Interaction glow on interactive objects
- [ ] Smaller hitbox trigger on the platform that falls (So you have to be on the platform for them to fall) (block on the upper platform?)
- [ ] Resume button bug, the mouse goes inactive so you have to press esc
- [ ] Falling into water should not be possible or be easier to get out of (R5)
- [ ] Information signs to the levers and interactive object/ information
- [ ] Create controler instructions and add to menu
- [ ] Dropping the spining thing is buggy af, hard to pick it up again, some time it disappears 
- [ ] more light after the water is removed, in front of the tunnel opening
- [ ] more light in the room with the desk (R11 / tunnel)
- [ ] Door size into the monsters bedroom
- [ ] You get stuck in the waterfall
- [ ] Lever on R10 is duplicated
- [ ] Bigger hitbox on levers

**Comment by DangelTheMangel** [comment]
Pause screen broky
