### ISSUE TITLE
founded problems from QA

### ISSUE THREAD

**Issue by Dange1TheMange1** [DiscoLucas/P7-Project#52]

**Comment by EmmaOtterlei** [comment]
- [ ] Missing lamp on C1 door
- [ ] The interactive object shader is ASSSSSS
- [ ]

**Comment by DangelTheMangel** [comment]
- [ ] Valve disapear
- [ ]

**Comment by DangelTheMangel** [comment]
- [ ] GOAP bot needs to be more aggressive
- [ ] Monster has to spawn closer to the start of the game
- [ ] Monster still gets stuck on doors and does not use vents soon enough
- [ ] Try and catch on foot step + jumping and landing sounds
- [ ] Door lights in R4 do not change after the lever in R4
- [ ] Make the LEver in R5 more visible (Either more light or tweak interact shader to have a longer range)
- [ ] Audio mixing
